namespace GeneradorRegistros
{
    public class Colecciones
    {

        public static List<string> Apellidos = new List<string>()
        {
            "GARCIA",
            "RODRIGUEZ",
            "GONZALEZ",
            "FERNANDEZ",
            "LOPEZ",
            "MARTINEZ",
            "SANCHEZ",
            "PEREZ",
            "GOMEZ",
            "MARTIN",
            "JIMENEZ",
            "HERNANDEZ",
            "RUIZ",
            "DIAZ",
            "MORENO",
            "MUÑOZ",
            "ALVAREZ",
            "ROMERO",
            "GUTIERREZ",
            "ALONSO",
            "NAVARRO",
            "TORRES",
            "DOMINGUEZ",
            "RAMOS",
            "VAZQUEZ",
            "RAMIREZ",
            "GIL",
            "SERRANO",
            "MORALES",
            "MOLINA",
            "BLANCO",
            "SUAREZ",
            "CASTRO",
            "ORTEGA",
            "DELGADO",
            "ORTIZ",
            "MARIN",
            "RUBIO",
            "NUÑEZ",
            "SANZ",
            "MEDINA",
            "IGLESIAS",
            "CASTILLO",
            "CORTES",
            "GARRIDO",
            "SANTOS",
            "GUERRERO",
            "LOZANO",
            "CANO",
            "MENDEZ",
            "CRUZ",
            "PRIETO",
            "FLORES",
            "HERRERA",
            "PEÑA",
            "LEON",
            "MARQUEZ",
            "CABRERA",
            "GALLEGO",
            "CALVO",
            "VIDAL",
            "CAMPOS",
            "REYES",
            "VEGA",
            "FUENTES",
            "CARRASCO",
            "DIEZ",
            "AGUILAR",
            "CABALLERO",
            "NIETO",
            "SANTANA",
            "PASCUAL",
            "HERRERO",
            "VARGAS",
            "GIMENEZ",
            "MONTERO",
            "HIDALGO",
            "LORENZO",
            "SANTIAGO",
            "IBAÑEZ",
            "DURAN",
            "BENITEZ",
            "FERRER",
            "ARIAS",
            "MORA",
            "CARMONA",
            "VICENTE",
            "ROJAS",
            "SOTO",
            "CRESPO",
            "ROMAN",
            "PASTOR",
            "VELASCO",
            "PARRA",
            "SAEZ",
            "MOYA",
            "BRAVO",
            "SOLER",
            "GALLARDO",
            "RIVERA"
        };


        public static List<string> Nombres = new List<string>()
        {
            "Rodrigo",
            "Marta",
            "Juan",
            "Sonia",
            "Antonio",
            "Raquel",
            "Humberto",
            "Susana",
            "Franciso",
            "Beatriz",
            "Julián",
            "Victoria",
            "Javier",
            "Elena",
            "Eduardo",
            "Ana",
            "Alberto",
            "Nuria",
            "Federico",
            "Alicia",
            "Rubén",
            "Irene",
            "Iván",
            "Inés",
            "Pablo",
            "Carmen",
            "Fernando",
            "Daniela",
            "Joaquín",
            "Ariana",
            "David",
            "Laura",
            "Miguel",
            "Isabel",
            "Ricardo",
            "Celia",
            "Manuel",
            "Eva",
            "Nicolás",
            "María",
            "Jesús",
            "Julia",
            "Rogelio",
            "Estrella",
            "Martín",
            "Lucía",
            "Raúl",
            "Amelia",
            "Álvaro",
            "Emilia",
            "Omar",
            "Aroa",
            "Óscar",
            "Catalina",
            "Gloria",
            "Julio",
            "Alba",
            "Vicente",
            "Natalia",
            "Marcos",
            "Carla",
            "Segio",
            "Sofía",
            "Mateo",
            "Oliver",
            "Elsa",
            "Santiago",
            "Sara",
            "Ismael",
            "Ruth",
            "Jaime",
            "Alma",
            "Alejandro",
            "Alejandra",
            "Burio",
            "Diana",
            "Víctor",
            "Cristina",
            "Rigoberto",
            "Pascuala",
            "Sinforoso",
            "Jimena",
            "Juan",
            "Marina",
            "Marco",
            "Olivia",
            "Luciano",
            "Valeria",
            "Sebastián",
            "Verónica",
            "Gustavo",
            "Emma",
            "Guillermo",
            "Andrea",
            "India",
            "Ramón",
            "Clara",
            "Gonzalo",
            "Alba",
            "Mariano",
            "Esther",
            "Felipe",
            "Luz",
            "Leo"
        };


        public static List<string> ViasNombre = new List<string>()
        {
            "Lagunas",
            "Camino Ancho",
            "Descubrimiento",
            "Ramón y Cajal",
            "General malapata",
            "La Paz",
            "Forasteros",
            "Olivar",
            "Bailes",
            "Primavera",
            "Del Pozo",
            "Nuncio",
            "Obispo Grande",
            "Atocha",
            "Amparo",
            "Cortes",
            "Arenal",
            "Paloma",
            "Pedro",
            "Cristóbal Colón",
            "Marconi",
            "Olvido",
            "Julian Grandre",
            "Los Exploradores",
            "Tuneladores",
            "Cruces",
            "Rio Seco",
            "Buenavista",
            "Cascorro",
            "Triodos",
            "Almendor",
            "Silva",
            "Priora",
            "Pastora",
            "Mediodia Chica",
            "Pastora",
            "Soledad",
            "Divertimento",
            "Gonzalo Ameristo",
            "Montera",
            "Abada",
            "La Solana",
            "Leganitos",
            "Botonera",
            "Lavanderas",
            "Cava Baja",
            "Bordadores",
            "Humilladero",
            "Sin salida",
            "Mayor",
            "Preciados",
            "Don Pedro",
            "Madrileños de fuera",
            "De la cabeza",
            "Mira del Río Alta",
            "Caba Alta",
            "Del Oso",
            "Serpientes",
            "Carros aparcados",
            "Siniestros",
            "Diestros",
            "Segovia",
            "Lavapies",
            "Señora Alta",
            "Señor bajito",
            "Embajadores",
            "Sombreros",
            "Leganitos",
            "Pascual el mayordomo",
            "Cristina de la cueva",
            "Matusalen",
            "Río Seco",
            "Postigo de San Martín",
            "La Bola Chiva",
            "Torre Mirador",
            "Mesón los Altos",
            "Espejo Roto",
            "Los Caminantes",
            "El Perro Galgo",
            "Toledo Antiguo",
            "Hilera",
            "Fucar",
            "Uvas Pasas",
            "Vendima",
            "Aguas Limpias",
            "El Marqués de Cubas",
            "El Oceano",
            "Tirso de Molina",
            "Metrópolis",
            "La Radio",
            "El Florero",
            "Las Pascuas Lejanas",
            "El Árbol Gordo",
            "El Lagurero",
            "Rías Frias",
            "Lechugas",
            "Lentejuelos",
            "Concepción del Arenal",
            "Junquillos",
            "Río Largo",
            "Laguna Seca",
            "Solidaridad Pasada",
            "Huecos",
            "Electrones",
            "Berenjeta",
            "El Morado",
            "Jaime el Conquistador",
            "Tribulere Tralará",
            "Caminante sin Freno",
            "Desamparados",
            "La Deuda",
            "Nubes",
            "Tierra Seca",
            "El Juncal",
            "La churrería",
            "San Isidro",
            "Las Huertas",
            "El Paso",
            "Gatos Pardos",
            "El Exilio",
            "Imigrantes",
            "Los Salvados",
            "Cristina la Cigarrera",
            "Lechugas Verdes",
            "Pimientos Verdes",
            "Labradores",
            "Espinos",
            "La Soledad",
            "Cocinillas",
            "Calderías",
            "Rayo Cesa",
            "La Calle 33",
            "Los Molinos",
            "El Halcón",
            "Venenos",
            "Lupa",
            "De la Fórmula One",
            "Del Fugado",
            "Amanecer",
            "La granja",
            "Camino de la Abadía",
            "Vega Baja",
            "Mesones",
            "Rivera Alta"
        };


        public static List<Provincia> ProvinciasCp =
           new List<Provincia>() {
            new Provincia() { Codigo="01", Nombre="Alava" },
            new Provincia() { Codigo="02", Nombre="Albacete" },
            new Provincia() { Codigo="03", Nombre="Alicante" },
            new Provincia() { Codigo="04", Nombre="Almería" },
            new Provincia() { Codigo="05", Nombre="Avila" },
            new Provincia() { Codigo="06", Nombre="Badajoz" },
            new Provincia() { Codigo="07", Nombre="Baleares" },
            new Provincia() { Codigo="08", Nombre="Barcelona" },
            new Provincia() { Codigo="09", Nombre="Burgos" },
            new Provincia() { Codigo="10", Nombre="Cáceres" },
            new Provincia() { Codigo="11", Nombre="Cádiz" },
            new Provincia() { Codigo="12", Nombre="Castellón" },
            new Provincia() { Codigo="13", Nombre="Ciudad Real" },
            new Provincia() { Codigo="14", Nombre="Córdoba" },
            new Provincia() { Codigo="15", Nombre="La Coruña" },
            new Provincia() { Codigo="16", Nombre="Cuenca" },
            new Provincia() { Codigo="17", Nombre="Gerona" },
            new Provincia() { Codigo="18", Nombre="Granada" },
            new Provincia() { Codigo="19", Nombre="Guadalajara" },
            new Provincia() { Codigo="20", Nombre="Guipúzcoa" },
            new Provincia() { Codigo="21", Nombre="Huelva" },
            new Provincia() { Codigo="22", Nombre="Huesca" },
            new Provincia() { Codigo="23", Nombre="Jaén" },
            new Provincia() { Codigo="24", Nombre="León" },
            new Provincia() { Codigo="25", Nombre="Lérida" },
            new Provincia() { Codigo="26", Nombre="La Rioja" },
            new Provincia() { Codigo="27", Nombre="Lugo" },
            new Provincia() { Codigo="28", Nombre="Madrid" },
            new Provincia() { Codigo="29", Nombre="Málaga" },
            new Provincia() { Codigo="30", Nombre="Murcia" },
            new Provincia() { Codigo="31", Nombre="Navarra" },
            new Provincia() { Codigo="32", Nombre="Orense" },
            new Provincia() { Codigo="33", Nombre="Oviedo" },
            new Provincia() { Codigo="34", Nombre="Palencia" },
            new Provincia() { Codigo="35", Nombre="Las Palmas" },
            new Provincia() { Codigo="36", Nombre="Pontevedra" },
            new Provincia() { Codigo="37", Nombre="Salamanca" },
            new Provincia() { Codigo="38", Nombre="Santa Cruz" },
            new Provincia() { Codigo="39", Nombre="Cantabria" },
            new Provincia() { Codigo="40", Nombre="Segovia" },
            new Provincia() { Codigo="41", Nombre="Sevilla" },
            new Provincia() { Codigo="42", Nombre="Soria" },
            new Provincia() { Codigo="43", Nombre="Tarragona" },
            new Provincia() { Codigo="44", Nombre="Teruel" },
            new Provincia() { Codigo="45", Nombre="Toledo" },
            new Provincia() { Codigo="46", Nombre="Valencia" },
            new Provincia() { Codigo="47", Nombre="Valladolid" },
            new Provincia() { Codigo="48", Nombre="Vizcaya" },
            new Provincia() { Codigo="49", Nombre="Zamora" },
            new Provincia() { Codigo="50", Nombre="Zaragoza" },
            new Provincia() { Codigo="51", Nombre="Ceuta" },
            new Provincia() { Codigo="52", Nombre="Melilla" }
           };


    }



    public class Provincia
    {
        public Provincia()
        {
            Codigo = "00";
            Nombre = string.Empty;
        }

        public string Codigo { get; set; }
        public string Nombre { get; set; }
    }
}